In [1]:
import numpy as np
import pandas as pd

In [2]:
demographic_df = pd.read_csv("CHSI dataset/DEMOGRAPHICS.csv")

In [3]:
demographic_df.head()

,State_FIPS_Code,County_FIPS_Code,CHSI_County_Name,CHSI_State_Name,CHSI_State_Abbr,Strata_ID_Number,Strata_Determining_Factors,Number_Counties,Population_Size,Min_Population_Size,...,Max_Black,Native_American,Min_Native_American,Max_Native_American,Asian,Min_Asian,Max_Asian,Hispanic,Min_Hispanic,Max_Hispanic
0,1,1,Autauga,Alabama,AL,29,"frontier status, population size, poverty, age",37,48612,28447,...,17.3,0.5,0.1,1.1,0.6,0.2,2.2,1.7,0.8,19.2
1,1,3,Baldwin,Alabama,AL,16,"frontier status, population size, poverty, age",27,162586,118395,...,14.1,0.5,0.1,1.1,0.4,0.4,3.3,2.3,0.8,13.7
2,1,5,Barbour,Alabama,AL,51,"frontier status, population size, poverty, age...",33,28414,27269,...,50.7,0.4,0.2,7.1,0.3,0.2,2.3,3.1,1.0,67.7
3,1,7,Bibb,Alabama,AL,42,"frontier status, population size, poverty, age",53,21516,8134,...,35.4,0.3,0.1,2.6,0.1,0.1,1.5,1.4,1.2,46.9
4,1,9,Blount,Alabama,AL,28,"frontier status, population size, poverty, age",39,55725,29009,...,20.5,0.5,0.1,0.9,0.2,0.3,2.2,6.3,0.8,6.3

In [4]:
demographic_df.columns

Index(['State_FIPS_Code', 'County_FIPS_Code', 'CHSI_County_Name',
       'CHSI_State_Name', 'CHSI_State_Abbr', 'Strata_ID_Number',
       'Strata_Determining_Factors', 'Number_Counties', 'Population_Size',
       'Min_Population_Size', 'Max_Population_Size', 'Population_Density',
       'Min_Population_Density', 'Max_Population_Density', 'Poverty',
       'Min_Poverty', 'Max_Poverty', 'Age_19_Under', 'Min_Age_19_Under',
       'Max_Age_19_Under', 'Age_19_64', 'Min_Age_19_64', 'Max_Age_19_65',
       'Age_65_84', 'Min_Age_65_84', 'Max_Age_65_85', 'Age_85_and_Over',
       'Min_Age_85_and_Over', 'Max_Age_85_and_Over', 'White', 'Min_White',
       'Max_White', 'Black', 'Min_Black', 'Max_Black', 'Native_American',
       'Min_Native_American', 'Max_Native_American', 'Asian', 'Min_Asian',
       'Max_Asian', 'Hispanic', 'Min_Hispanic', 'Max_Hispanic'],
      dtype='object')

In [5]:
col = ["State_FIPS_Code", "CHSI_State_Name","County_FIPS_Code", "CHSI_County_Name", "CHSI_State_Abbr",
                         "Strata_ID_Number", "Strata_Determining_Factors", "Number_Counties", "Population_Size", "Poverty",
                         "Age_19_Under", "Age_19_64", "Age_65_84", "Age_85_and_Over", "White", "Black", "Native_American", "Asian", "Hispanic"]
demographic_df = demographic_df[col]
demographic_df.head()

,State_FIPS_Code,CHSI_State_Name,County_FIPS_Code,CHSI_County_Name,CHSI_State_Abbr,Strata_ID_Number,Strata_Determining_Factors,Number_Counties,Population_Size,Poverty,Age_19_Under,Age_19_64,Age_65_84,Age_85_and_Over,White,Black,Native_American,Asian,Hispanic
0,1,Alabama,1,Autauga,AL,29,"frontier status, population size, poverty, age",37,48612,10.4,26.9,62.3,9.8,0.9,80.7,17.3,0.5,0.6,1.7
1,1,Alabama,3,Baldwin,AL,16,"frontier status, population size, poverty, age",27,162586,10.2,23.5,60.3,14.5,1.8,88.4,9.9,0.5,0.4,2.3
2,1,Alabama,5,Barbour,AL,51,"frontier status, population size, poverty, age...",33,28414,22.1,24.3,62.5,11.6,1.6,52.2,46.8,0.4,0.3,3.1
3,1,Alabama,7,Bibb,AL,42,"frontier status, population size, poverty, age",53,21516,16.8,24.6,63.3,10.9,1.2,76.8,22.5,0.3,0.1,1.4
4,1,Alabama,9,Blount,AL,28,"frontier status, population size, poverty, age",39,55725,11.9,24.5,62.1,12.1,1.3,97.1,1.5,0.5,0.2,6.3

In [6]:
demographic_df.dtypes

State_FIPS_Code                 int64
CHSI_State_Name                object
County_FIPS_Code                int64
CHSI_County_Name               object
CHSI_State_Abbr                object
Strata_ID_Number                int64
Strata_Determining_Factors     object
Number_Counties                 int64
Population_Size                 int64
Poverty                       float64
Age_19_Under                  float64
Age_19_64                     float64
Age_65_84                     float64
Age_85_and_Over               float64
White                         float64
Black                         float64
Native_American               float64
Asian                         float64
Hispanic                      float64
dtype: object

In [7]:
demographic_df.count()

State_FIPS_Code               3141
CHSI_State_Name               3141
County_FIPS_Code              3141
CHSI_County_Name              3141
CHSI_State_Abbr               3141
Strata_ID_Number              3141
Strata_Determining_Factors    3141
Number_Counties               3141
Population_Size               3141
Poverty                       3141
Age_19_Under                  3141
Age_19_64                     3141
Age_65_84                     3141
Age_85_and_Over               3141
White                         3141
Black                         3141
Native_American               3141
Asian                         3141
Hispanic                      3141
dtype: int64

In [8]:
s = demographic_df["Poverty"]
any(x < 0 for x in s)

True

In [9]:
from sqlalchemy import create_engine

In [10]:
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, Float

In [11]:
!pip install psycopg2
!pip install psycopg2-binary

Collecting psycopg2
  Using cached https://files.pythonhosted.org/packages/84/d7/6a93c99b5ba4d4d22daa3928b983cec66df4536ca50b22ce5dcac65e4e71/psycopg2-2.8.4.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'

    Error: pg_config executable not found.

    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.

    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).


    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/wc/lm96ywfx48z4v9pgjfjl9hwh0000gn/T/pip-install-awjueoys/psycopg2/
Requirement already satisfied: psycopg2-binary in /Users/bhavinivyas/anaconda3/lib/python3.7/site-packages (2.8.3)

In [12]:
# https://docs.sqlalchemy.org/en/13/dialects/postgresql.html#module-sqlalchemy.dialects.postgresql.psycopg2
# postgresql+psycopg2://user:password@host:port/dbname[?key=value&key=value...]

user = "postgres"
password = "changeme"
host = "localhost"
port = "5432" # 5432 for everyone else
db = "CHSI_db"
uri = f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{db}"
uri

'postgresql+psycopg2://postgres:changeme@localhost:5432/CHSI_db'

In [13]:
Base = declarative_base()
class User(Base):
    __tablename__ = "demographic_data"
    State_FIPS_Code = Column(Integer, primary_key=True)     
    CHSI_State_Name = Column(String(255))
    County_FIPS_Code = Column(Integer, primary_key=True)
    CHSI_County_Name = Column(String(255))
    CHSI_State_Abbr = Column(String(255))
    Strata_ID_Number =  Column(Integer)     
    Strata_Determining_Factors = Column(String(255))
    Number_Counties =  Column(Integer)     
    Population_Size =  Column(Integer)     
    Poverty = Column(Float)
    Age_19_Under = Column(Float)
    Age_19_64 = Column(Float)
    Age_65_84 = Column(Float)
    Age_85_and_Over = Column(Float)
    White = Column(Float)
    Black = Column(Float)
    Native_American = Column(Float)
    Asian = Column(Float)
    Hispanic = Column(Float)

In [14]:
# Create the connection engine
engine = create_engine(uri)
conn = engine.connect()

In [15]:
# Base.metadata.drop_all(conn)
Base.metadata.create_all(conn)

In [16]:
demographic_df.to_sql(User.__tablename__, conn, index=False, if_exists="append")

In [18]:
# demographic_df["County_FIPS_Code"].value_counts()
dup = demographic_df[demographic_df["County_FIPS_Code"] == 55]
dup.head()

,State_FIPS_Code,CHSI_State_Name,County_FIPS_Code,CHSI_County_Name,CHSI_State_Abbr,Strata_ID_Number,Strata_Determining_Factors,Number_Counties,Population_Size,Poverty,Age_19_Under,Age_19_64,Age_65_84,Age_85_and_Over,White,Black,Native_American,Asian,Hispanic
27,1,Alabama,55,Etowah,AL,6,"frontier status, population size, poverty",53,103189,15.7,24.0,60.3,13.9,1.8,83.8,14.6,0.3,0.5,2.4
136,5,Arkansas,55,Greene,AR,50,"frontier status, population size, poverty, age...",27,39401,15.4,25.3,60.9,12.2,1.6,97.8,0.3,0.4,0.2,1.5
211,6,California,55,Napa,CA,13,"frontier status, population size, poverty, age",16,132764,7.9,24.7,60.8,12.1,2.4,89.3,2.0,1.0,5.6,27.3
270,8,Colorado,55,Huerfano,CO,87,"frontier status, population size, poverty, age",32,7771,19.2,20.4,61.0,15.9,2.8,91.9,3.0,3.3,0.6,34.3
344,12,Florida,55,Highlands,FL,24,"frontier status, population size, poverty, age",35,95496,13.9,20.0,48.9,26.7,4.3,88.0,9.6,0.5,1.3,15.0

In [29]:
riskfactor_df = pd.read_csv("CHSI dataset/RISKFACTORSANDACCESSTOCARE.csv")

In [30]:
riskfactor_df.head()

,State_FIPS_Code,County_FIPS_Code,CHSI_County_Name,CHSI_State_Name,CHSI_State_Abbr,Strata_ID_Number,No_Exercise,CI_Min_No_Exercise,CI_Max_No_Exercise,Few_Fruit_Veg,...,Diabetes,CI_Min_Diabetes,CI_Max_Diabetes,Uninsured,Elderly_Medicare,Disabled_Medicare,Prim_Care_Phys_Rate,Dentist_Rate,Community_Health_Center_Ind,HPSA_Ind
0,1,1,Autauga,Alabama,AL,29,27.8,20.7,34.9,78.6,...,14.2,9.1,19.3,5690,4762,1209,45.3,22.6,1,2
1,1,3,Baldwin,Alabama,AL,16,27.2,23.2,31.2,76.2,...,7.2,5.2,9.3,19798,22635,3839,67.0,30.8,1,2
2,1,5,Barbour,Alabama,AL,51,-1111.1,-1111.1,-1111.1,-1111.1,...,6.6,2.0,11.3,5126,3288,1092,45.8,24.6,1,2
3,1,7,Bibb,Alabama,AL,42,-1111.1,-1111.1,-1111.1,86.6,...,13.1,4.7,21.5,3315,2390,974,41.8,18.6,1,1
4,1,9,Blount,Alabama,AL,28,33.5,26.3,40.6,74.6,...,8.4,4.4,12.4,8131,5019,1300,16.2,10.8,2,1

In [31]:
riskfactor_df.loc[~(riskfactor_df["No_Exercise"] > 0), "No_Exercise"]=np.nan

In [32]:
riskfactor_df.head()

,State_FIPS_Code,County_FIPS_Code,CHSI_County_Name,CHSI_State_Name,CHSI_State_Abbr,Strata_ID_Number,No_Exercise,CI_Min_No_Exercise,CI_Max_No_Exercise,Few_Fruit_Veg,...,Diabetes,CI_Min_Diabetes,CI_Max_Diabetes,Uninsured,Elderly_Medicare,Disabled_Medicare,Prim_Care_Phys_Rate,Dentist_Rate,Community_Health_Center_Ind,HPSA_Ind
0,1,1,Autauga,Alabama,AL,29,27.8,20.7,34.9,78.6,...,14.2,9.1,19.3,5690,4762,1209,45.3,22.6,1,2
1,1,3,Baldwin,Alabama,AL,16,27.2,23.2,31.2,76.2,...,7.2,5.2,9.3,19798,22635,3839,67.0,30.8,1,2
2,1,5,Barbour,Alabama,AL,51,NaN,-1111.1,-1111.1,-1111.1,...,6.6,2.0,11.3,5126,3288,1092,45.8,24.6,1,2
3,1,7,Bibb,Alabama,AL,42,NaN,-1111.1,-1111.1,86.6,...,13.1,4.7,21.5,3315,2390,974,41.8,18.6,1,1
4,1,9,Blount,Alabama,AL,28,33.5,26.3,40.6,74.6,...,8.4,4.4,12.4,8131,5019,1300,16.2,10.8,2,1

In [33]:
num = riskfactor_df._get_numeric_data()
num.head()
num[num < 0] = np.nan
riskfactor_df.head()

,State_FIPS_Code,County_FIPS_Code,CHSI_County_Name,CHSI_State_Name,CHSI_State_Abbr,Strata_ID_Number,No_Exercise,CI_Min_No_Exercise,CI_Max_No_Exercise,Few_Fruit_Veg,...,Diabetes,CI_Min_Diabetes,CI_Max_Diabetes,Uninsured,Elderly_Medicare,Disabled_Medicare,Prim_Care_Phys_Rate,Dentist_Rate,Community_Health_Center_Ind,HPSA_Ind
0,1,1,Autauga,Alabama,AL,29,27.8,20.7,34.9,78.6,...,14.2,9.1,19.3,5690,4762,1209,45.3,22.6,1,2
1,1,3,Baldwin,Alabama,AL,16,27.2,23.2,31.2,76.2,...,7.2,5.2,9.3,19798,22635,3839,67.0,30.8,1,2
2,1,5,Barbour,Alabama,AL,51,NaN,NaN,NaN,NaN,...,6.6,2.0,11.3,5126,3288,1092,45.8,24.6,1,2
3,1,7,Bibb,Alabama,AL,42,NaN,NaN,NaN,86.6,...,13.1,4.7,21.5,3315,2390,974,41.8,18.6,1,1
4,1,9,Blount,Alabama,AL,28,33.5,26.3,40.6,74.6,...,8.4,4.4,12.4,8131,5019,1300,16.2,10.8,2,1
5,1,11,Bullock,Alabama,AL,75,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2295,1433,504,54.3,18.1,1,1
6,1,13,Butler,Alabama,AL,76,24.5,15.5,33.5,NaN,...,9.5,4.4,14.6,4055,3150,952,43.3,19.3,1,2
7,1,15,Calhoun,Alabama,AL,6,29.2,25.1,33.3,81.9,...,11.2,8.4,13.9,16456,16440,5301,75.8,41.9,1,2
8,1,17,Chambers,Alabama,AL,50,34.7,25.3,44.0,84.6,...,17.1,10.2,24.1,5533,5473,1497,53.6,22.6,1,2
9,1,19,Cherokee,Alabama,AL,64,NaN,NaN,NaN,NaN,...,13.3,6.8,19.8,3583,3086,854,28.5,12.2,2,1
10,1,21,Chilton,Alabama,AL,32,30.3,23.1,37.5,82.8,...,6.0,3.2,8.9,6130,4527,1307,31.1,19.2,1,2
11,1,23,Choctaw,Alabama,AL,66,NaN,NaN,NaN,NaN,...,13.5,6.6,20.3,2677,2148,800,33.8,20.3,1,1
12,1,25,Clarke,Alabama,AL,51,31.5,22.0,41.1,NaN,...,15.8,8.2,23.4,4593,3850,1150,55.0,29.3,2,2
13,1,27,Clay,Alabama,AL,63,NaN,NaN,NaN,NaN,...,12.2,4.4,20.0,2320,2198,610,35.8,14.3,2,1
14,1,29,Cleburne,Alabama,AL,41,NaN,NaN,NaN,NaN,...,10.5,3.6,17.5,2107,1852,646,0.0,6.9,2,1
15,1,31,Coffee,Alabama,AL,32,23.3,17.2,29.4,NaN,...,10.3,4.1,16.6,6764,6099,1366,48.3,39.5,1,2
16,1,33,Colbert,Alabama,AL,21,30.2,23.3,37.2,76.9,...,13.6,8.9,18.3,8141,8226,2302,60.4,31.1,1,2
17,1,35,Conecuh,Alabama,AL,75,NaN,NaN,NaN,NaN,...,8.2,2.9,13.6,2657,1947,725,60.3,7.5,1,1
18,1,37,Coosa,Alabama,AL,41,NaN,NaN,NaN,NaN,...,15.0,6.1,24.0,2028,1562,621,9.0,9.0,1,1
19,1,39,Covington,Alabama,AL,35,28.8,21.1,36.6,NaN,...,12.1,6.8,17.5,6094,6401,1583,59.5,24.3,1,2
20,1,41,Crenshaw,Alabama,AL,71,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2504,2272,568,14.6,14.6,1,1
21,1,43,Cullman,Alabama,AL,21,29.4,23.9,34.9,76.2,...,10.0,6.5,13.5,11912,11129,2400,53.8,22.5,1,2
22,1,45,Dale,Alabama,AL,33,30.4,22.8,37.9,79.5,...,12.1,7.4,16.7,7831,7809,2314,24.6,22.6,2,1
23,1,47,Dallas,Alabama,AL,52,31.5,23.9,39.1,85.9,...,11.5,7.2,15.7,9242,6424,2302,101.4,38.3,1,2
24,1,49,DeKalb,Alabama,AL,24,37.0,30.4,43.6,80.7,...,7.8,4.6,11.0,12260,8411,2351,34.2,19.3,1,2
25,1,51,Elmore,Alabama,AL,19,27.7,22.0,33.4,85.0,...,5.5,3.2,7.8,8320,7792,2167,33.8,16.2,1,2
26,1,53,Escambia,Alabama,AL,51,34.3,26.3,42.3,87.1,...,11.4,6.3,16.5,6490,5064,1476,57.8,26.3,1,2
27,1,55,Etowah,Alabama,AL,6,34.1,29.6,38.5,81.4,...,10.2,7.5,12.9,16180,15265,4508,72.7,42.6,1,2
28,1,57,Fayette,Alabama,AL,63,NaN,NaN,NaN,NaN,...,12.7,6.6,18.8,2358,2544,731,60.3,16.5,2,2
29,1,59,Franklin,Alabama,AL,49,28.9,19.0,38.9,85.5,...,7.2,2.9,11.6,5977,4871,1320,35.8,22.8,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3111,55,129,Washburn,Wisconsin,WI,59,NaN,NaN,NaN,NaN,...,7.0,0.6,13.5,1925,3810,558,72.3,24.1,1,2
3112,55,131,Washington,Wisconsin,WI,12,17.8,13.9,21.8,78.1,...,3.3,1.6,5.0,6870,14177,1543,55.5,44.4,2,2
3113,55,133,Waukesha,Wisconsin,WI,10,16.6,13.9,19.3,73.4,...,5.2,3.9,6.5,23728,47091,4364,140.1,72.8,2,2
3114,55,135,Waupaca,Wisconsin,WI,18,24.3,18.7,29.8,83.2,...,5.6,2.9,8.3,3788,9549,1117,62.8,26.6,2,2
3115,55,137,Waushara,Wisconsin,WI,60,18.5,12.4,24.6,76.1,...,9.3,4.7,13.9,2688,3988,574,40.3,20.2,1,1
3116,55,139,Winnebago,Wisconsin,WI,11,19.4,16.1,22.6,83.4,...,8.7,6.5,10.8,10463,19804,2677,97.8,48.9,1,2
3117,55,141,Wood,Wisconsin,WI,45,22.6,18.1,27.1,75.7,...,7.5,5.0,10.1,4893,13077,1497,215.3,70.4,1,2
3118,56,1,Albany,Wyoming,WY,32,15.0,12.8,17.3,71.7,...,4.1,3.0,5.2,5182,2666,418,97.1,45.3,2,2
3119,56,3,Big Horn,Wyoming,WY,82,23.7,20.0,27.4,80.6,...,6.5,4.2,8.7,2036,1811,244,35.3,44.1,1,2
3120,56,5,Campbell,Wyoming,WY,47,24.2,21.8,26.6,82.0,...,4.2,3.2,5.3,4995,1959,406,72.2,32.1,2,2
3121,56,7,Carbon,Wyoming,WY,80,24.6,21.2,28.1,80.6,...,6.2,4.6,7.9,2446,1896,295,52.2,45.7,2,1
3122,56,9,Converse,Wyoming,WY,80,21.4,17.8,24.9,80.4,...,6.3,4.4,8.2,1893,1438,192,54.8,15.7,2,1
3123,56,11,Crook,Wyoming,WY,78,25.1,20.2,30.0,82.6,...,5.4,2.8,7.9,815,843,89,32.4,16.2,2,2
3124,56,13,Fremont,Wyoming,WY,77,21.3,19.1,23.5,76.6,...,6.9,5.5,8.3,6855,4962,847,90.4,60.3,1,2
3125,56,15,Goshen,Wyoming,WY,84,25.1,21.6,28.6,77.5,...,7.4,5.2,9.6,2424,2182,254,81.7,24.5,2,2
3126,56,17,Hot Springs,Wyoming,WY,81,24.4,18.9,29.9,74.4,...,7.3,4.1,10.5,799,950,151,88.2,66.1,2,1
3127,56,19,Johnson,Wyoming,WY,81,20.5,16.2,24.9,76.3,...,6.0,3.3,8.7,1227,1326,138,103.6,38.9,2,2
3128,56,21,Laramie,Wyoming,WY,17,20.8,19.3,22.3,78.7,...,6.1,5.3,7.0,11401,9736,1762,83.4,47.0,1,2
3129,56,23,Lincoln,Wyoming,WY,78,18.9,15.9,21.9,72.7,...,4.4,3.0,5.8,2166,1862,172,56.3,50.0,2,2
3130,56,25,Natrona,Wyoming,WY,20,22.5,20.9,24.2,80.7,...,6.4,5.4,7.3,10067,8504,1425,87.4,48.7,1,2
3131,56,27,Niobrara,Wyoming,WY,84,25.1,18.5,31.7,75.4,...,4.8,0.0,9.7,407,447,40,0.0,43.7,2,1
3132,56,29,Park,Wyoming,WY,77,20.3,18.0,22.7,78.8,...,5.3,4.1,6.5,4119,4040,477,112.5,48.8,1,2
3133,56,31,Platte,Wyoming,WY,81,22.8,18.7,27.0,82.2,...,6.3,4.1,8.5,1548,1535,197,34.8,34.8,2,1
3134,56,33,Sheridan,Wyoming,WY,30,20.2,17.8,22.5,77.5,...,6.9,5.5,8.4,3705,4044,560,73.0,47.5,2,2
3135,56,35,Sublette,Wyoming,WY,78,22.6,18.1,27.2,81.9,...,5.0,2.8,7.3,795,763,69,72.2,14.4,2,2
3136,56,37,Sweetwater,Wyoming,WY,77,21.9,19.8,24.1,80.7,...,5.3,4.2,6.4,5477,3260,572,50.0,52.7,2,1
3137,56,39,Teton,Wyoming,WY,78,9.6,7.3,11.9,68.8,...,2.4,1.4,3.4,1846,1393,82,147.1,57.8,2,2
3138,56,41,Uinta,Wyoming,WY,38,23.4,20.5,26.3,83.1,...,4.8,3.4,6.2,3007,1431,357,65.2,40.1,2,1
3139,56,43,Washakie,Wyoming,WY,82,23.2,18.8,27.6,78.1,...,9.4,6.6,12.1,1178,1338,136,50.4,50.4,1,1
3140,56,45,Weston,Wyoming,WY,78,31.3,26.1,36.6,75.4,...,5.7,3.4,8.0,867,1072,143,45.0,30.0,2,1

In [34]:
riskfactor_df.count()

State_FIPS_Code                3141
County_FIPS_Code               3141
CHSI_County_Name               3141
CHSI_State_Name                3141
CHSI_State_Abbr                3141
Strata_ID_Number               3141
No_Exercise                    2206
CI_Min_No_Exercise             2206
CI_Max_No_Exercise             2206
Few_Fruit_Veg                  1904
CI_Min_Fruit_Veg               1904
CI_Max_Fruit_Veg               1904
Obesity                        2224
CI_Min_Obesity                 2224
CI_Max_Obesity                 2224
High_Blood_Pres                1522
CI_Min_High_Blood_Pres         1522
CI_Max_High_Blood_Pres         1522
Smoker                         2267
CI_Min_Smoker                  2267
CI_Max_Smoker                  2267
Diabetes                       2719
CI_Min_Diabetes                2719
CI_Max_Diabetes                2719
Uninsured                      3141
Elderly_Medicare               3141
Disabled_Medicare              3141
Prim_Care_Phys_Rate            3141
Dentist_Rate                   3140
Community_Health_Center_Ind    3141
HPSA_Ind                       3141
dtype: int64

In [36]:
col = ["State_FIPS_Code", "County_FIPS_Code", "No_Exercise", "Few_Fruit_Veg", 
       "Obesity", "Smoker", "Diabetes", "Uninsured", "Prim_Care_Phys_Rate", "Dentist_Rate", "Community_Health_Center_Ind"]
    
riskfactor_df = riskfactor_df[col]
riskfactor_df.head()

,State_FIPS_Code,County_FIPS_Code,No_Exercise,Few_Fruit_Veg,Obesity,Smoker,Diabetes,Uninsured,Prim_Care_Phys_Rate,Dentist_Rate,Community_Health_Center_Ind
0,1,1,27.8,78.6,24.5,26.6,14.2,5690,45.3,22.6,1
1,1,3,27.2,76.2,23.6,24.6,7.2,19798,67.0,30.8,1
2,1,5,NaN,NaN,25.6,17.7,6.6,5126,45.8,24.6,1
3,1,7,NaN,86.6,NaN,NaN,13.1,3315,41.8,18.6,1
4,1,9,33.5,74.6,24.2,23.6,8.4,8131,16.2,10.8,2